### ISSUE TITLE
Component syntax questions

### ISSUE THREAD

**Issue by gliechtenstein** [mwlang/jasonette-rails#1]
Awesome I am loving it so far! Just one question regarding the syntax:

Looks like all components have a single primary attribute used for representing the content, for example in case of an `image` we have an image url, like so:

```
image image_url("rails-logo.png") do
  style do
    align "center"
    padding "30"
  end
end
```

I have a couple of questions regarding the syntax, especially about the primary attribute

### 1. What happens if we want to represent a component that doesn't have a single primary attribute? 
For example, [textfield](http://docs.jasonette.com/components/#textfield) has a `name` and a `value` attributes which are both mandatory. 

Also [map](http://docs.jasonette.com/components/#map) has two attributes that represent content--`region` and `pins`--which in turn have their own child attributes. 

### 2. How to upgrade/migrate components?

Let's say we initially created a `label` component to take `text` as the primary attribute. The current syntax would be:

```
label "Hello world" do
  style do
    color "#ff0000"
  end
end
```

What if for some reason we want to change the attribute name to `content` while deprecating the `text` attribute (BUT NOT breaking all the old code).

In case of Jasonette, you can simply add another attribute to the object and it will work for both `content` and `text` attributes. For example, below code would work for older versions as well as the newer versions. Older ones will just look at `text` and the newer ones will just look at `content`. Gradually we can phase out `text`.

```
{
  "type": "label",
  "text": "Hello World",
  "content": "Hello World"
}
```

I may be misunderstanding the code but I think with the current syntax structure, every time some attribute gets deprecated we will need to update this library to handle the new mapping correctly.

For example in the following code, if Jasonette adds a `content` attribute in place of `text` (not saying it will, I'm just making a hypothetical point), we will need to come back and update this code to make sure `caption` maps to `content` as well as `text`. (Whereas if we treat `text` the same as any other attribute and leave it up to the `with_attributes` line, there's nothing to maintain)

```
    def label caption=nil
      item = Jasonette::Base.new(@context) do
        text caption unless caption.nil?
        type "label"
        with_attributes { instance_eval(&::Proc.new) } if block_given?
      end
      append item
    end
```

Maybe there's a good way to do this with the current syntax I'm totally missing. Please let me know.

**Comment by mwlang** [comment]
To point #1, components that have two mandatory fields, it's as simple as having two parameters.  Or we can remove that part of the syntax altogether.  The primary motivation for me was that I wanted be able whip up interfaces fast, even if I haven't thought just what each label's action's going to be, yet.  For example:
~~~ruby
items do
   label "foo"
   label "bar"
end
~~~
Even so, it was my expectation that most often developers would opt to do:

~~~ruby
label do
   text "Foo"
   # ...
end
~~~

So this might be syntax sugar worth omitting to avoid maintenance headaches down the road.  After all, now that I think about it, could've easily done quick labels as:

~~~ruby
items do
   label { text "Foo" }
   label { text "Bar" }
end
~~~

To point #2, handling deprecations....well, it's my hope Jasonette's implementation will solidify relatively quickly and minimize this issue altogether.  But even so, first parameters plugging a specific attribute actually helps "old code" not to break on such deprecation changes.  Lets say you renamed the attribute for label components from "text" to "caption".  Then if developers were using the ```label "foo" do ...``` format, then if we updated the gem to plug ```caption``` instead of ```text``` to match new Jasonette structure, then the developer's project code wins in this case.

So I guess the fundamental question here is, "do we want to support parameters on component builders or not?"  My general feeling is, yes, support it where it makes sense, otherwise, don't.  In the case of map, my natural inclination would be to *NOT* have parameters on the map builder since the mandatory fields aren't scalar properties anyway.

**Comment by gliechtenstein** [comment]
Yup as a user, I'm totally fine as long as there's an option to do both and use the simpler version as a syntactic sugar :) Thanks for the thorough answer! 👍
